language: rust
sudo: false
cache: cargo

rust:
  - 1.34.0
  - stable

install:
  - export PATH=$PATH:~/.cargo/bin
  - command -v cargo-web >/dev/null 2>&1 || cargo install cargo-web

script: 
  - cargo build --all --verbose --exclude dashboard
  - cargo test --all --verbose --exclude dashboard
  - cargo web build --verbose
  - cargo doc --all --verbose

before_deploy:
  - cargo doc --all --verbose
  - cd dashboard && cargo web build --release --verbose --output dist && cd ..
  - mkdir -p public
  - cp -r target/doc public/crate-docs
  - cp -r dashboard/dist public/dashboard
  - echo '<meta http-equiv="refresh" content="0; url=core/index.html" /> ' > public/crate-docs/index.html
  - echo '<meta http-equiv="refresh" content="0; url=dashboard/index.html" /> ' > public/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  local_dir: public
  on:
    branch: master
