[package]
name = "easy-374"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "../core" }
smallvec = "0.6.9"

[lib]
path = "lib.rs"
